root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  bin = "./cmd/server"  # Ensure this points to your binary
  cmd = "make build"    # Adjust if your build process differs
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = ["./internal", "./pkg"]  # Add directories specific to your project
  include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]  # Add extensions as needed
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = true  # Enable timestamps for better debugging

[misc]
  clean_on_exit = true  # Clean up temporary files on exit

[screen]
  clear_on_rebuild = true  # Clear screen on rebuild for better readability
  keep_scroll = true
