services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      API_KEY: ${API_KEY}
      WAHA_URL: ${WAHA_URL}
      TEXT_BLAST_TEMPLATE: ${TEXT_BLAST_TEMPLATE}
      BLASTER_WEBHOOK_URL: ${BLASTER_WEBHOOK_URL}
      PORT: ${PORT}
      APP_ENV: ${APP_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SCHEMA: ${DB_SCHEMA}
      BASE_WEBFORM_URL: ${BASE_WEBFORM_URL}
      PROMO_CODE: ${PROMO_CODE}
    ports:
      - "${PORT:-8080}:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s