-- +goose Up
-- +goose StatementBegin
CREATE TABLE "vouchers" (
	"id" BIGINT NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"type" VARCHAR(255) NOT NULL,
	"amount" DOUBLE PRECISION NOT NULL,
	"name" VARCHAR(255) NOT NULL UNIQUE,
	PRIMARY KEY("id")
);


CREATE INDEX "vouchers_index_0"
ON "vouchers" ("id", "name");
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE "vouchers";
DROP INDEX "vouchers_index_0"
-- +goose StatementEnd
