// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PromoTracker struct {
	ID           int64
	HashedString string
	ExpiredAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	Claimed      bool
	UserName     string
}
