// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PromoTracker struct {
	ID           int64
	HashedString string
	ExpiredAt    pgtype.Timestamptz
	CreatedAt    pgtype.Timestamptz
	Claimed      bool
	UserName     string
	UpdatedAt    pgtype.Timestamptz
	Voucher      pgtype.Text
	ClaimedAt    pgtype.Timestamptz
	IsProcessed  bool
	SentToTm     bool
	ProcessNote  pgtype.Text
	UserID       pgtype.Text
}

type Voucher struct {
	ID                 int64
	Type               string
	Amount             float64
	Name               string
	PromoDurationHours int32
	TopupDeadline      pgtype.Int4
	PromoTextTemplate  pgtype.Text
}
