// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: phone_number_not_exists.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPhoneNumberNotExist = `-- name: CreatePhoneNumberNotExist :one
INSERT INTO "phone_number_not_exist" ("phone_number", "username", "blast_id")
VALUES ($1, $2, $3)
RETURNING phone_number, username, blast_id
`

type CreatePhoneNumberNotExistParams struct {
	PhoneNumber string
	Username    pgtype.Text
	BlastID     pgtype.UUID
}

func (q *Queries) CreatePhoneNumberNotExist(ctx context.Context, arg CreatePhoneNumberNotExistParams) (PhoneNumberNotExist, error) {
	row := q.db.QueryRow(ctx, createPhoneNumberNotExist, arg.PhoneNumber, arg.Username, arg.BlastID)
	var i PhoneNumberNotExist
	err := row.Scan(&i.PhoneNumber, &i.Username, &i.BlastID)
	return i, err
}
