// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package repository

import (
	"context"
)

const getAllTrackedPromos = `-- name: GetAllTrackedPromos :many
SELECT id, hashed_string, expired_at, created_at, claimed, user_name FROM "promo_tracker"
ORDER BY id DESC
`

func (q *Queries) GetAllTrackedPromos(ctx context.Context) ([]PromoTracker, error) {
	rows, err := q.db.Query(ctx, getAllTrackedPromos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromoTracker
	for rows.Next() {
		var i PromoTracker
		if err := rows.Scan(
			&i.ID,
			&i.HashedString,
			&i.ExpiredAt,
			&i.CreatedAt,
			&i.Claimed,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
