// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vouchers.sql

package repository

import (
	"context"
)

const getOneVoucher = `-- name: GetOneVoucher :one
SELECT id, type, amount, name, promo_duration_hours FROM "vouchers"
WHERE "name" = $1
`

func (q *Queries) GetOneVoucher(ctx context.Context, name string) (Voucher, error) {
	row := q.db.QueryRow(ctx, getOneVoucher, name)
	var i Voucher
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Amount,
		&i.Name,
		&i.PromoDurationHours,
	)
	return i, err
}
